#!/bin/sh
#define the variables beneath
GZIP=$(which gzip)
MARIABACKUP=$(which mariabackup)
USER=oneadmin
DB=opennebula
NOW=$(date '+%M%H%d')
FILE=mbackup-$NOW.gz
BDIR=/backup/hourly
$MARIABACKUP --backup --databases=$DB --user=$USER --stream=xbstream | $GZIP > $BDIR/$FILE
